language: node_js
cache:
  directories:
    - node_modules
    - ~/.nmp
node_js:
  - '12'
git:
  depth: 3
script:
  - yarn test
notifications:
  email:
    recipients:
      - erickson_flelly@hotmail.com
    on_success: always
    on_failure: always
deploy:
  provide: heroku
  skip-cleanup: true
  keep-history: true
  api_key: 
  "FNZkeg1c8CoQj5bDtCMGorybAEt06fHL/DowZkwpFG2C0Ucatn/1qBJgY12daTl4PfIylgWfOjxOjJu7cFV2z7q8wiWID9zH+g/v3ygvSUMZ1b9+SZ3XhFsrEp2qwRguO6dg+TS6iPo7Eiet9c4yTBzjzTIPsjDCa2qoME71swyAS+7orUlr+fRikbfuvG5F3VtsrNewcObv3+zFwNBo0bKRZV4BZkMLgtwevzC34ZGJVr9jRbiHEPOgQJrILfsY/N7tkLpNtKyyIY0IDzf61VOhZRmbwfMVFVXiFZW3IoTMygHkz53Ar0xgaH9xhc+PMGNYfgfH0tS05IC0EFhlHx1RgSWTnu1hTOR0iH+RYdNdBAW/T9ljgi2jAo7rivBC3AgTlx3Rub7gvsi59rrR7XuL22EmHS23UYrUJIP1UsamVL81Vdx3vPjJCbKmjn8wXHoNF7a6t+8dkudsTIdBqXr6D3f8TCk/Rdb7zXc988FCxHLSc6Ab0/Bi507QkPXG30JRdQrh6weyvnTrX7oeVerHontCMF6tjFg9ngDfV6MSVSU1pByQMBlAriVB7GUDcRONkx+EPMZvp07g3Z/ZHkcTAR/xcpYDy7IjGRTRVawSi9iALkxRmV6ZSq4gbsCNBYFxH/Q3W6peE9wLJjmoBG5MzLu1IHh/cvnbEAiRI2U="
  app: platzi-store-backend777
  on:
    repo: erikseals/platzi-store-backend

