language: node_js
cache:
  directories:
    - node_modules
    - ~/.nmp
node_js:
  - '12'
git:
  depth: 3
script:
  - yarn test
notifications:
  email:
    recipients:
      - erickson_flelly@hotmail.com
    on_success: always
    on_failure: always
deploy:
  provide: heroku
  skip-cleanup: true
  keep-history: true
  api_key: ebf443f1-5259-4ee1-99bd-e9b6120c1825
  app: platzi-store-backend777
  on:
    repo: erikseals/platzi-store-backend

